name: iOS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '2.19.0'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'

    - name: Print Dart version
      run: dart --version

    - name: Print Flutter version
      run: flutter --version

    - name: Flutter Pub Get
      run: |
        flutter pub get
        if [ $? -ne 0 ]; then
          cat pubspec.lock
          cat pubspec.yaml
        fi

    - name: Install Pods
      run: |
        cd ios
        pod install

    - name: Build iOS
      run: flutter build ios --no-codesign
