name: iOS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Download and Install Dart SDK
      run: |
        wget https://storage.googleapis.com/dart-archive/channels/stable/release/2.19.0/sdk/dartsdk-macos-arm64-release.zip
        unzip dartsdk-macos-arm64-release.zip -d $HOME/.dart-sdk
        echo 'export PATH="$HOME/.dart-sdk/dart-sdk/bin:$PATH"' >> $GITHUB_ENV

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'

    - name: Print Dart version
      run: dart --version

    - name: Print Flutter version
      run: flutter --version

    - name: Flutter Pub Get
      run: |
        flutter pub get
        if [ $? -ne 0 ]; then
          echo "pub get failed. Displaying pubspec.lock:"
          cat pubspec.lock
          echo "Displaying pubspec.yaml:"
          cat pubspec.yaml
          exit 1
        fi

    - name: Install Pods
      run: |
        cd ios
        pod install

    - name: Build iOS
      run: flutter build ios --no-codesign
