name: iOS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Install Pods
      run: |
        cd ios
        pod install

    - name: Build iOS
      run: flutter build ios --no-codesign
